### ISSUE TITLE
Invoke-IntuneManagedDeviceWipeDevice should not require macOsUnlockCode as mandatory

### ISSUE THREAD

**Issue by patlewis-MSFT** [microsoft/Intune-PowerShell-SDK#50] opened 2019-07-02 19:53 UTC
One of the parameters for Invoke-IntuneManagedDeviceWipeDevice is not applicable to Android or Win devices but still requires a macOsUnlockCode.

See ManagedDevices.cs
        [Parameter(**Mandatory = true,** ValueFromPipelineByPropertyName = true, HelpMessage = @"The &quot;macOsUnlockCode&quot; action parameter of type &quot;Edm.String&quot;.")]
        public System.String macOsUnlockCode { get; set; }

**Comment by rohitramu** [comment] 2019-07-11 05:29
Duplicate of #51.

**Closed by rohitramu** 2019-07-11 05:29 UTC
